# Generated by Django 5.1.1 on 2024-09-17 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_initial'),
        ('revisions', '0003_alter_revision_file_s3_key'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
