# Generated by Django 5.1.1 on 2024-09-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_rename_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='audio_s3_key',
            field=models.FileField(blank=True, null=True, upload_to='comments/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image_s3_key',
            field=models.FileField(blank=True, null=True, upload_to='comments/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
